language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm run test:ci
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
before_install:
- export TZ=America/Toronto
